# Mean-Variance-Standard Deviation Calculator

In [1]:
import pandas as pd
import numpy as np

In [18]:
#List = [] 
#while len(List) < 9:
    #A = int(input('Enter a number')) 
   # List.append(A)

#print(List) 

In [21]:
def calculate (List):
 
    result = {}
    row_means, row_vars, row_stds, row_maxs, row_mins, row_sums = [], [], [], [], [], []
    col_means, col_vars, col_stds, col_maxs, col_mins, col_sums = [], [], [], [], [], []

    if len(List) < 9:
        print("List must contain nine numbers")
    elif len(List) == 9:
        c = np.array(List)
        c = c.reshape(3,3)
        print(c)
        for r in range(0,3):
            
            row_mean = c[r].mean()
            row_var = c[r].var()
            row_std = c[r].std()
            row_max = c[r].max()
            row_min = c[r].min()
            row_sum = c[r].sum()
            
            # Appending the row operations
            row_means.append(row_mean)
            row_vars.append(row_var)
            row_stds.append(row_std)
            row_maxs.append(row_max)
            row_mins.append(row_min)
            row_sums.append(row_sum)
            
            col_mean =c[:,r].mean()
            col_var = c[:,r].var()
            col_std = c[:,r].std()
            col_max = c[:,r].max()
            col_min = c[:,r].min()
            col_sum = c[:,r].sum()
            
             # Appending the row operations
            col_means.append(col_mean)
            col_vars.append(col_var)
            col_stds.append(col_std)
            col_maxs.append(col_max)
            col_mins.append(col_min)
            col_sums.append(col_sum)
        #print(row_means)
        result["mean"] = [col_means,row_means,c.mean()]
        result["variance"] = [row_vars,col_vars,c.var()]
        result["standard deviation"] = [row_stds,col_stds,c.std()]
        result["max"] = [row_maxs,col_maxs,c.max()]
        result["min"] = [row_mins,col_mins,c.min()]
        result["sum"] = [row_sums,col_sums,c.sum()]
        print(result)


In [23]:
calculate([2,6,2,8,4,0,1,5,7])

[[2 6 2]
 [8 4 0]
 [1 5 7]]
{'mean': [[3.3333333333333335, 4.0, 4.333333333333333], [3.6666666666666665, 5.0, 3.0], 3.888888888888889], 'variance': [[3.555555555555556, 10.666666666666666, 6.222222222222221], [9.555555555555557, 0.6666666666666666, 8.666666666666666], 6.987654320987654], 'standard deviation': [[1.8856180831641267, 3.265986323710904, 2.494438257849294], [3.091206165165235, 0.816496580927726, 2.943920288775949], 2.6434171674156266], 'max': [[6, 8, 7], [8, 6, 7], 8], 'min': [[2, 0, 1], [1, 4, 0], 0], 'sum': [[10, 12, 13], [11, 15, 9], 35]}


In [ ]:
def imput([]):
    pri